Additional EV Subsidy Percentage[passenger,LDVs] = 4609.18
Additional PHEV Subsidy[passenger,LDVs] = 4380.25
Passenger Vehicle Cost Reduction due to Battery Production Credit[LDVs,battery electric vehicle] = 1740.04
Passenger Vehicle Cost Reduction due to Battery Production Credit[LDVs,plugin hybrid vehicle] = 358.95
Policy Implementation Schedule Selector = 5
Renewable Portfolio Std Percentage = 0.0898
